services:
    store_backendbundle.flash_messenger:
        class: Store\BackendBundle\Messenger\Flash
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}
