#Page list of products
store_backend_product_list:
   path:     /list
   defaults: {_controller: 'StoreBackendBundle:Product:list'}

#Page view product
store_backend_product_view:
    path:        /view/{id}/{name}
    requirements:
        id:      \d+
        name:    (.){5,50}
        _method: GET
    defaults:    {_controller: 'StoreBackendBundle:Product:view'}

#Page delete product
store_backend_product_delete:
    path:        /delete/{id}
    requirements:
        id:      \d+
        _method: GET
    defaults:    {_controller: 'StoreBackendBundle:Product:delete'}

#Page creation product
store_backend_product_new:
    path:        /new
    requirements:
        _method: GET|POST
    defaults:    {_controller: 'StoreBackendBundle:Product:new'}