#Page supplier list
store_backend_supplier_list:
    path:     /list
    defaults: {_controller: 'StoreBackendBundle:Supplier:list'}

#Page supplier view
store_backend_supplier_view:
    path: /view/{id}/{name}
    requirements:
        id: \d+
        name: ([A-z\-?]){3,30}
        _method: GET
    defaults: {_controller: 'StoreBackendBundle:Supplier:view'}

#Page delete supplier
store_backend_supplier_delete:
    path:        /delete/{id}
    requirements:
        id:      \d+
        _method: GET
    defaults:    {_controller: 'StoreBackendBundle:Supplier:delete'}

#Page delete supplier
store_backend_supplier_new:
    path:        /new
    requirements:
        _method: GET|POST
    defaults:    {_controller: 'StoreBackendBundle:Supplier:new'}

store_backend_supplier_activate:
    path: /activate/{id}/{active}
    requirements:
        id: \d+
        active: \d{1}
    defaults: {_controller: 'StoreBackendBundle:Supplier:activate'}